import type { LifecycleStage } from "./types";

export const lifecycleStages: LifecycleStage[] = [
  {
    id: "startup",
    name: "Startup",
    size: "1–20 people",
    summary:
      "Searching for a repeatable business model while surviving on limited runway.",
    structure: "No formal org chart. Everyone reports to the founder(s); titles are aspirational.",
    managementStyle: "Founder-driven, direct, high-energy. Communication happens by proximity — overheard conversations replace meetings.",
    departments: "None formally. One person handles finance, another 'does marketing' alongside building product.",
    decisionMaking: "Minutes. Decisions happen in hallway conversations; speed is the core advantage.",
    processes: "Almost none deliberately — everything is improvised, which is correct at this stage.",
    technology: "Off-the-shelf tools (Notion, Stripe, no-code) chosen for speed over scalability.",
    hiring: "Hiring is existential and rare: generalists who tolerate chaos, believe the mission, and accept equity-heavy compensation.",
    challenges: [
      "Finding product-market fit before money runs out",
      "Founders doing everything, becoming bottlenecks",
      "First hires shaping culture permanently — often accidentally",
      "Distinguishing 'no traction yet' from 'wrong direction'",
    ],
  },
  {
    id: "small-business",
    name: "Small Business",
    size: "10–50 people",
    summary:
      "A working business model with steady revenue — now professionalizing without killing momentum.",
    structure: "First real teams emerge around functions: engineering, sales, admin. Founders still involved in most decisions.",
    managementStyle: "Founder-led but delegating selectively. First managers hired or promoted; founder learns to let go.",
    departments: "Proto-departments form: a finance person, an HR function, distinct sales and marketing.",
    decisionMaking: "Fast but documented. Weekly leadership meetings appear; some decisions get written down.",
    processes: "Key processes documented where quality matters (onboarding, invoicing); the rest stays informal.",
    technology: "Proper systems arrive: CRM, accounting software, HR tools replacing spreadsheets.",
    hiring: "Specialists join — first controller, first recruiter. Every hire still visibly moves the company.",
    challenges: [
      "Founders transitioning from doers to managers (classic failure point)",
      "Communication degrading as proximity disappears",
      "Culture defined intentionally before it defines itself badly",
      "Cash flow management as payrolls grow faster than collections",
    ],
  },
  {
    id: "growth",
    name: "Growth Stage",
    size: "50–200 people",
    summary:
      "Scaling what works, fast. Often venture-funded with aggressive targets and growing pains.",
    structure: "Real org chart with departments, managers of managers, and the first Directors/VPs.",
    managementStyle: "Middle management layer becomes real. OKRs or similar frameworks cascade goals; founders focus outward.",
    departments: "All major departments exist with their own budgets, headcount plans, and internal politics.",
    decisionMaking: "Slower and more political. Cross-team coordination requires meetings, docs, and explicit prioritization.",
    processes: "Processes formalize company-wide: review cycles, planning rituals, procurement rules.",
    technology: "Internal tooling teams build infrastructure; technical debt becomes a strategic topic.",
    hiring: "Volume hiring with structured interviews. Employer branding matters; attrition becomes measurable.",
    challenges: [
      "Coordination costs exploding faster than output",
      "Early employees feeling displaced by experienced hires",
      "Culture dilution across new locations/teams",
      "Maintaining innovation speed while adding process",
    ],
  },
  {
    id: "medium-company",
    name: "Medium Company",
    size: "200–1,000 people",
    summary:
      "An established organization optimizing efficiency, expanding markets, and defending position.",
    structure: "Multi-layer hierarchy with VPs owning departments, directors owning functions, matrix reporting common.",
    managementStyle: "Professional management dominates. Strategy set annually through formal planning; execution tracked quarterly.",
    departments: "Full department suites including Legal, Procurement, IT, Security, possibly multiple product lines each with sub-teams.",
    decisionMaking: "Committee-based for significant items. Decision rights documented; escalation paths defined.",
    processes: "Mature SOPs, audit trails, compliance programs. Change management becomes its own discipline.",
    technology: "Integrated systems landscape (ERP, data warehouse); dedicated platform teams; security/compliance tooling.",
    hiring: "Employer-brand driven recruiting with talent pipelines. Internal mobility programs; succession planning starts.",
    challenges: [
      "Bureaucracy creeping into decisions that used to take hours",
      "Silo formation between departments",
      "Innovation competing with operational excellence for resources",
      "Retaining entrepreneurial talent inside structure",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    size: "1,000+ people",
    summary:
      "Market incumbent managing complexity at scale — or preparing the next transformation.",
    structure: "Divisions, regions, global functions. Multiple org layers; matrix structures spanning geographies and products.",
    managementStyle: "Institutionalized leadership. Governance boards, steering committees, formal strategy cycles.",
    departments: "Everything specialized — sometimes hundreds of distinct functions, plus shared services organizations.",
    decisionMaking: "Deliberate and process-heavy. Significant approvals traverse committees; risk management gates spending.",
    processes: "Extensively documented and audited. Regulatory compliance shapes daily operations.",
    technology: "Massive integrated estates: legacy systems coexisting with modern platforms; huge security apparatus.",
    hiring: "Global recruiting machines, university programs, employer brand managed like a product.",
    challenges: [
      "Disruption vulnerability: startups attacking profitable niches",
      "Change velocity: transformations measured in years",
      "Ownership diffusion — nobody feels accountable for whole outcomes",
      "Rekindling startup energy when needed (internal incubators, acquisitions)",
    ],
  },
];
