import type { GeneratedTestData } from "@/core/types";

export type ExportFormat = "json" | "csv" | "js" | "ts" | "playwright" | "cypress";

function buildFixtureObject(data: GeneratedTestData): Record<string, unknown> {
  return {
    test_id: data.id,
    provider: data.provider,
    scenario: data.scenario,
    expected_result: data.expectedResult,
    customer: {
      full_name: data.customer.fullName,
      email: data.customer.email,
      phone: data.customer.phone,
      address: data.customer.address,
    },
    card: data.card
      ? {
          number: data.card.number,
          expiry: data.card.expiry,
          cvc: data.card.cvc,
          brand: data.card.brand,
        }
      : null,
    metadata: {
      sandbox_only: true,
      provider_docs: data.docsUrl,
    },
  };
}

export function toJson(data: GeneratedTestData): string {
  return JSON.stringify(buildFixtureObject(data), null, 2);
}

function escapeCsv(value: unknown): string {
  const str = String(value ?? "");
  if (/[",\n]/.test(str)) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export function toCsv(data: GeneratedTestData): string {
  const headers = [
    "provider",
    "scenario",
    "expected_result",
    "full_name",
    "email",
    "phone",
    "address_line1",
    "address_line2",
    "city",
    "state",
    "zip",
    "country",
    "card_number",
    "expiry",
    "cvc",
  ];
  const row = [
    data.provider,
    data.scenario,
    data.expectedResult,
    data.customer.fullName,
    data.customer.email,
    data.customer.phone,
    data.customer.address.line1,
    data.customer.address.line2 ?? "",
    data.customer.address.city,
    data.customer.address.state,
    data.customer.address.zip,
    data.customer.address.country,
    data.card?.number ?? "",
    data.card?.expiry ?? "",
    data.card?.cvc ?? "",
  ];
  return [headers.map(escapeCsv).join(","), row.map(escapeCsv).join(",")].join("\n");
}

export function toJsFixture(data: GeneratedTestData, varName = "testFixture"): string {
  return `// Generated by TestCard Lab - SANDBOX / TEST ONLY
const ${varName} = ${JSON.stringify(buildFixtureObject(data), null, 2)};

module.exports = ${varName};
`;
}

export function toTsFixture(data: GeneratedTestData, interfaceName = "TestFixture"): string {
  return `// Generated by TestCard Lab - SANDBOX / TEST ONLY
export interface ${interfaceName} {
  test_id: string;
  provider: string;
  scenario: string;
  expected_result: string;
  customer: {
    full_name: string;
    email: string;
    phone: string;
    address: {
      line1: string;
      line2?: string;
      city: string;
      state: string;
      zip: string;
      country: string;
    };
  };
  card: {
    number: string | null;
    expiry: string;
    cvc: string;
    brand: string;
  } | null;
}

export const testFixture: ${interfaceName} = ${JSON.stringify(
    buildFixtureObject(data),
    null,
    2,
  )};
`;
}

export function toPlaywrightExample(data: GeneratedTestData): string {
  return `// Playwright example - SANDBOX / TEST ONLY
// Run: npx playwright test
import { test, expect } from "@playwright/test";

test("sandbox checkout - ${data.provider}: ${data.scenario}", async ({ page }) => {
  await page.goto("http://localhost:3000");
  await page.getByLabel("Email").fill("${data.customer.email}");
  await page.getByLabel("Full name").fill("${data.customer.fullName}");
  await page.getByLabel("Card number").fill("${data.card?.number ?? "«documented sandbox number»"}");
  await page.getByLabel("Expiry").fill("${data.card?.expiry ?? "12/28"}");
  await page.getByLabel("CVC").fill("${data.card?.cvc ?? "123"}");
  await page.getByRole("button", { name: "Pay" }).click();

  // ${data.expectedResult}
  await expect(page.getByText("Success")).toBeVisible();
});
`;
}

export function toCypressExample(data: GeneratedTestData): string {
  return `// Cypress example - SANDBOX / TEST ONLY
describe("sandbox checkout - ${data.provider}: ${data.scenario}", () => {
  it("exercises the ${data.scenario} flow", () => {
    cy.visit("/checkout");
    cy.get('[data-testid="email"]').type("${data.customer.email}");
    cy.get('[data-testid="full-name"]').type("${data.customer.fullName}");
    cy.get('[data-testid="card-number"]').type("${data.card?.number ?? "«documented sandbox number»"}");
    cy.get('[data-testid="expiry"]').type("${data.card?.expiry ?? "1228"}");
    cy.get('[data-testid="cvc"]').type("${data.card?.cvc ?? "123"}");
    cy.get('[data-testid="pay-button"]').click();

    // ${data.expectedResult}
    cy.contains("Success").should("be.visible");
  });
});
`;
}

export function downloadFile(
  filename: string,
  content: string,
  mimeType: string,
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function makeFilename(
  data: GeneratedTestData,
  extension: string,
): string {
  return `testcard-${data.provider}-${data.scenario}.${extension}`;
}
